### ISSUE TITLE
enrich returns  undefined method `downcase' for nil:NilClass

### ISSUE THREAD

**Issue by beniutek** [PRX/open_calais#12]
Hello,
I have a strange error when using the gem. 
error is undefined method `downcase' for nil:NilClass and is happening at

https://github.com/PRX/open_calais/blob/master/lib/open_calais/response.rb#L50

The string I send to the OpenCalais API is
 "The rival group of bondholders has asked shareholders to vote against GSO’s plans at a Jan. 6 meeting, according to a letter seen by Bloomberg. " (it's part of a bigger article, but I have managed to locate where the issue is happening"

When we remove "The rival group of" from the string then it the response is correct and we get no error. After digging in a bit, here is the interesting part of the response:

```
 "http://d.opencalais.com/genericHasher-1/2e1b93e6-9ca4-3eb1-8ae9-34a2b8b2b413"=>
  {"_typeGroup"=>"entities",
   "_type"=>"IndustryTerm",    <<--- no name field here
   "forenduserdisplay"=>"false",
   "_typeReference"=>"http://s.opencalais.com/1/type/em/e/IndustryTerm",
   "instances"=>
    [{"detection"=>"[The ]rival group[ of bondholders has asked shareholders to vote]",
      "prefix"=>"The ",
      "exact"=>"rival group",
      "suffix"=>" of bondholders has asked shareholders to vote",
      "offset"=>4,
      "length"=>11}],
   "relevance"=>0.2},
 "http://d.opencalais.com/comphash-1/edf6d19b-1098-30a9-bca6-241d2dfdc12b"=>
  {"_typeGroup"=>"entities",
   "_type"=>"Company",
   "forenduserdisplay"=>"false",
   "name"=>"Bloomberg",         <<--- here we have name field
   "nationality"=>"N/A",
   "confidencelevel"=>"0.905",
   "resolutions"=>[{"name"=>"BLOOMBERG L.P.", "permid"=>"4295956702", "commonname"=>"Bloomberg", "score"=>1, "id"=>"https://permid.org/1-4295956702"}],
   "confidence"=>{"statisticalfeature"=>"0.876", "dblookup"=>"0.0", "resolution"=>"1.0", "aggregate"=>"0.905"},
   "_typeReference"=>"http://s.opencalais.com/1/type/em/e/Company",
   "instances"=>
    [{"detection"=>"[a Jan. 6 meeting, according to a letter seen by ]Bloomberg[. ]",
      "prefix"=>"a Jan. 6 meeting, according to a letter seen by ",
      "exact"=>"Bloomberg",
      "suffix"=>". ",
      "offset"=>133,
      "length"=>9}],
   "relevance"=>0}}
```

As you can see, there is no :name field for IndustryTerm type.

without this name, when we try to evaluate condition in line 50 (from the first link) we get nil.downcase that is obviously bad.

Right now, I forked the gem to check what can I change to fix this and just added the line that ensures `item[:name]` will always have a value. I was initial thinking to change in line 50 `item[:name].downcase` to `item[:name].to_s.downcase` but that would interfere too much with the logic in this method. For me, reason of this issue is the response we get from Open Calais API gem, but maybe you have already encountered such issue and know what to do?

**Comment by kookster** [comment]
Haven't seen this before, I've only seen entities with name attributes.
I see the change you made in your fork (i.e. getting the `:exact` from the first instance when there is no name), and I would accept that as a PR.

**Comment by beniutek** [comment]
do you know maybe, is it possible that there are no instances in the response?

**Comment by kookster** [comment]
idk, as far as I knew there were no entities without names, and I don't see guarantees in the docs for instances or names

**Comment by kookster** [comment]
I do see this in the docs: "Every entity markup tag has one or more associated instances.", which implies there should be instances for entities.

**Comment by beniutek** [comment]
I'll make a PR soon, just need to move it to separate branch. Thanks for your help!

**Comment by mamut** [comment]
I believe #13 should fix this issue, any chance of merging it?

**Comment by tbrammar** [comment]
:+1: it fixes this issue. Please merge #13

**Comment by kookster** [comment]
merged (finally)
